trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  # 1. ETAPA DE CONSTRUCCIÓN (CI)
  - stage: Build
    displayName: 'Build'
    jobs:
      - job: BuildJob
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Instalar Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'Compilar React / Vite'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/dist'
              artifact: 'drop'
            displayName: 'Publicar Artefacto'

  # 2. ETAPA DE DESPLIEGUE EN DEV
  - stage: Deploy_DEV
    displayName: 'Deploy DEV'
    dependsOn: Build
    jobs:
      - deployment: DeployDEVJob
        environment: 'DEV'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                - script: echo "Desplegando en ambiente DEV..."
                  displayName: 'Ejecutar despliegue DEV'

  # 3. ETAPA DE DESPLIEGUE EN QA
  - stage: Deploy_QA
    displayName: 'Deploy QA'
    dependsOn: Deploy_DEV
    jobs:
      - deployment: DeployQAJob
        environment: 'QA'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                - script: echo "Desplegando en ambiente QA..."
                  displayName: 'Ejecutar despliegue QA'

  # 4. ETAPA DE DESPLIEGUE EN PDN (Requiere aprobación manual)
  - stage: Deploy_PDN
    displayName: 'Deploy PDN'
    dependsOn: Deploy_QA
    jobs:
      - deployment: DeployPDNJob
        environment: 'PDN'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                - script: echo "Desplegando en ambiente PDN..."
                  displayName: 'Ejecutar despliegue PDN'