trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: DEV
    displayName: "Deploy DEV"
    jobs:
      - deployment: DeployDEV
        displayName: "Deploy DEV"
        environment: 'DEV'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: NodeTool@0
                  inputs:
                    versionSpec: '18.x'
                  displayName: "Instalar Node.js"

                - script: npm ci
                  displayName: "Instalar dependencias"

                - script: npm test
                  displayName: "Ejecutar pruebas unitarias (Jest)"

                - script: echo "Build/Test exitoso y despliegue simulado en DEV"
                  displayName: "Despliegue DEV"

  - stage: QA
    displayName: "Deploy QA"
    dependsOn: DEV
    condition: succeeded()
    jobs:
      - deployment: DeployQA
        displayName: "Deploy QA"
        environment: 'QA'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Despliegue simulado en QA (APP_ENVIRONMENT=QA)"
                  displayName: "Despliegue QA"

  - stage: PDN
    displayName: "Deploy PDN"
    dependsOn: QA
    condition: succeeded()
    jobs:
      - deployment: DeployPDN
        displayName: "Deploy PDN"
        environment: 'PDN'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Despliegue exitoso en Producción (APP_ENVIRONMENT=PDN)"
                  displayName: "Despliegue PDN"